Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbwt_m3_mvc.Models;

namespace dbwt_m3_mvc.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            if (!string.IsNullOrEmpty(Session["user"] as string)) {
                return Redirect("LogoutForm");
            }
            return Redirect("LoginForm");
        }

        public ActionResult LoginForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoginForm(FormCollection form)
        {
            if (string.IsNullOrEmpty(form["loginname"]) || string.IsNullOrEmpty(form["password"])) {
                if (string.IsNullOrEmpty(form["loginname"]))
                    ModelState.AddModelError("loginname", "Bitte Benutzernamen eingeben");
                if (string.IsNullOrEmpty(form["password"]))
                    ModelState.AddModelError("password", "Bitte Passwort eingeben");

                return View();
            }

            else {
                FENutzer user = FENutzer.GetByCredentials(form["loginname"], form["password"]);
                if (user != null) {
                    Session["user"] = user.Vorname;
                    Session["role"] = user.Role;

                    if (user.LetzterLogin.CompareTo(new DateTime(1, 1, 1, 1, 1, 1)) > 0) 
                        TempData["flash"] = "Hallo " + user.Vorname + ", Sie sind angemeldet als " + user.Role + " und waren zuletzt am " + user.LetzterLogin + " bei uns!";
                    else
                        TempData["flash"] = "Hallo " + user.Vorname + ", Sie sind angemeldet als " + user.Role + " und besuchen uns zum ersten Mal. Herzlich Willkommen!";
                }
                else
                    TempData["flash"] = "Benutzername oder Passwort falsch, oder das Konto wurde noch nicht aktiviert";
            }
            if (Request.UrlReferrer.PathAndQuery.Equals("/Login/LoginForm"))
                return RedirectToAction("Index", "Home");
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult LogoutForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogoutForm(FormCollection form)
        {
            if (!string.IsNullOrEmpty(Session["user"] as string)) {
                Session.Remove("role");
                Session.Remove("user");
                TempData["flash"] = "Sie haben sich erfolgreich abgemeldet";
            }
            if (Request.UrlReferrer.PathAndQuery.Equals("/Login/LogoutForm"))
                return RedirectToAction("Index", "Home");
            else
                return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

Controllers/ProduktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbwt_m3_mvc.Models;

namespace dbwt_m3_mvc.Controllers
{
    public class ProduktController : Controller
    {
        // GET: Produkt
        public ActionResult Index() {
            ViewBag.Kategorie = "Bestseller";
            if (int.TryParse(Request.Params["category"], out int catId) && catId > 0) {
                Kategorie kat = Kategorie.GetById(catId);
                if (kat != null)
                    ViewBag.Kategorie = kat.Bezeichnung;
                else
                    catId = 0;
            }
            else
                catId = 0;

            if (!int.TryParse(Request.Params["limit"], out int limit) || limit <= 0)
                limit = 8;

            ViewBag.Kategorien = Kategorie.GetList();
            ViewBag.Produkte = Produkt.GetList(catId, limit);
            return View();
        }

       public ActionResult Detail(int id) {
            string role = "gast";
            if (!string.IsNullOrEmpty(Session["role"] as string))
                role = Session["role"].ToString();
            Produkt produkt = Produkt.GetByID(id);
            if (produkt != null)
                return View(produkt);
            return Redirect("Index");
        }
    }
}

Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbwt_m3_mvc.Models;

namespace dbwt_m3_mvc.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index(FENutzer user) {
            return View();
        }

        public ActionResult Create() {
            return View();
        }
        
        [HttpPost]
        public ActionResult Create(FENutzer user, FormCollection form) {
            if (ModelState.IsValid) {
                if (!user.Password.Equals(user.PasswordConfirm)) {
                    ModelState.AddModelError("passwordconfirm", "Die Passwörter stimmen nicht überein");
                    return View("Create", user);
                }
                
                if (!FENutzer.CheckEMail(user.EMail)) {
                    ModelState.AddModelError("email", "Diese E-Mail-Adresse wird bereits verwendet");
                    return View("Create", user);
                }

                if (!FENutzer.CheckLoginname(user.Loginname)) {
                    ModelState.AddModelError("loginname", "Dieser Benutzername wird bereits verwendet");
                    return View("Create", user);
                }

                TempData["user"] = user;

                switch (form["role"]) {
                    case "student":
                        return RedirectToAction("CreateStudent");

                    case "mitarbeiter":
                        return RedirectToAction("CreateMitarbeiter");

                    default:
                        return RedirectToAction("CreateGast");
                }
            }
            return View("Create", user);
        }


        public ActionResult CreateStudent() {
            return View();
        }

        [HttpPost]
        public ActionResult CreateStudent(Student student) {
            if (!ModelState.IsValid)
                return View("Create", student);

            student.Save(TempData["user"] as FENutzer);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult CreateMitarbeiter(){
            return View();
        }

        [HttpPost]
        public ActionResult Mitarbeiter(Mitarbeiter mitarbeiter) {
            if (!ModelState.IsValid)
                return View("Create", mitarbeiter);

            mitarbeiter.Save(TempData["user"] as FENutzer);

            return RedirectToAction("Index", "Home");
        }


        public ActionResult CreateGast(){
            return View();
        }

        [HttpPost]
        public ActionResult CreateGast(Gast gast) {
            if (!ModelState.IsValid)
                return View("Create", gast);

            gast.Save(TempData["user"] as FENutzer);
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>e-Mensa - @ViewBag.Title</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!--<link rel="stylesheet" href="static/bootstrap-3.3.7-dist/css/bootstrap.min.css">-->
    <!-- custom stylesheet -->
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @RenderSection("head", required: false)

</head>
<body>
    <div class="wrapper">
        <div class="container">
            <header class="row">
                <div class="col-md-2">
                    <h1>e-Mensa</h1>
                </div>
                <div class="col-md-7">
                    <nav id="nav-main">
                        <ul class="">
                            <li>@Html.ActionLink("Start", "Index", "Home")</li>
                            <li>@Html.ActionLink("Mahlzeiten", "Index", "Produkt")</li>
                            <li><a href="#">Bestellung</a></li>
                            <li><a href="http://fh-aachen.de" target="_blank" class="last">FH-Aachen</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-3">
                    <form class="" id="search" role="search" action="https://www.google.de/" method="get" target="_blank">
                        <button class="" id="search-btn" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                        <input class="" id="search-text" type="text" placeholder="Suchen..." name="q" />
                        <input type="text" hidden name="as_sitesearch" value="www.fh-aachen.de" />
                    </form>
                </div>
            </header>
            <div class="row">
                <div class="col-md-12">
                    @TempData["flash"]
                </div>
            </div>
        </div> <!-- container (header) -->

        <div class="container">
            @RenderBody()
        </div> <!-- container (body) -->

        <div class="container">
            <footer class="row">
                <div class="col-md-2" id="copyright">
                    &copy; 2017 DBWT
                </div>
                <div class="col-md-8">
                    <nav class="nav-footer">
                        <ul class="">
                            @{
                                if (!string.IsNullOrEmpty(Session["user"] as string)) {
                                    @:<li>@Html.ActionLink("Logout", "LogoutForm", "Login")</li>
                                }
                                else {
                                    @:<li>@Html.ActionLink("Login", "LoginForm", "Login")</li>
                                    @:<li>@Html.ActionLink("Registrieren", "Create", "Register")</li>
                                }
                            }
                            <li><a href="#">Zutatenliste</a></li>
                            <li>@Html.ActionLink("Impressum", "Index", "Impressum")</li>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-2">
                    @DateTime.Now
                </div>
            </footer>
        </div> <!-- container (footer) -->
    </div> <!-- wrapper -->
    <!-- Scripts -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified Bootstrap-JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Messages.cshtml
<div class="" id="messgaes">
    @ViewBag.Message
</div>